---
title: "On the origin of citations"
author: "Ittai Eres"
date: "September 15, 2015"
output:
  html_document:
    toc: true
    number_sections: true
    theme: cerulean
    highlight: espresso
    fig_width: 8
    fig_height: 8
    fig_caption: yes
    self_contained: false
---

#Load the data, suckaaaaaaa!
##using read.delim
```{r load_data}
counts_raw <- read.delim("data/counts-raw.txt.gz")
counts_norm <- read.delim("data/counts-norm.txt.gz")
```
#Data exploration.
What's the distributiuon of authors in all articles of our data set?
```{r author_histogram, fig.cap="Figure 1: Number of Authors per Article", echo=FALSE}
hist(counts_raw$authorsCount, main= "Authors per paper", xlab="# authors", ylab="# papers", breaks=50, xlim=range(0,50))
```

How many facebook likes do articles tend to get?
```{r facebook_likes_histogram, echo=FALSE}
hist(counts_raw$facebookShareCount, main="FB Shares per paper", xlab="Likes", ylab="# papers", breaks = 500, xlim=range(0,50))
```

The average number of Facebook shares per paper in the data set is `r mean(counts_raw$facebookShareCount)`


You can use `render("name_of_markdown_file")` to make an html knit without it popping up.
```{r}

```

